apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*

build:
  # local:
  # push: false
  # googleCloudBuild:
  #  projectId: ticketo-dev
  local:
    push: false
  artifacts:
    - image: vijethab/auth
    # - image: us.gcr.io/ticketo-dev/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: vijethab/client
    # - image: us.gcr.io/ticketo-dev/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/**/*.js'
            dest: .
    - image: vijethab/tickets
    # - image: us.gcr.io/ticketo-dev/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: vijethab/orders
    # - image: us.gcr.io/ticketo-dev/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: vijethab/expiration
    # - image: us.gcr.io/ticketo-dev/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: vijethab/payments        
    # - image: us.gcr.io/ticketo-dev/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
